
EXTRA_CFLAGS += -I$(src)/include -I$(src)/arch/$(ARCH)/include
ifdef VERBOSITY
EXTRA_CFLAGS += -DMONMOD_LOG_VERBOSITY=$(VERBOSITY)
endif
obj-m += monmod.o
cflags-y := -I$(src)/include -I$(src)/arch/$(ARCH)/include 
monmod-y := \
	src/main.o \
	src/config.o \
	src/util.o \
	src/tracepoint_helpers.o \
	src/custom_syscalls.o \
	src/tracee_info.o \
	src/xxhash.o
